name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.restore-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: npm ci

  verify:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: ["fmt:check", "textlint", "astro check"]
    steps:
      - uses: actions/checkout@v5
      - name: restore cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: run ${{ matrix.task }}
        run: npm run ${{ matrix.task }}
